services:
  - type: web
    name: trip-planner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SERPAPI_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
